config/routes.rb
MailDump::Engine.routes.draw do
  root :to => "logged_mail#index"
  resources :logged_mail
end

app/models/logged_mail.rb
require 'mail/fields/common/address_container'

class LoggedMail < ActiveRecord::Base
  # attr_accessible :body, :from, :html, :raw, :subject, :to, :reply_to

  serialize :from
  serialize :reply_to
  serialize :to
  serialize :body
  serialize :html

  def has_text?
    self.body.present?
  end

  def has_html?
    self.html.present?
  end

  def from_addresses
    from.respond_to?(:join) ? from.join(',') : from
  end

  def to_addresses
    to.respond_to?(:join) ? to.join(',') : to
  end
  
  #
  # implement #delivered_mail observer to log mail after the fact
  #
  def self.delivered_email(message)
    # firgure out if the body is html or text
    if message.multipart?
      html = message.html_part
      text = message.text_part
    else
      if message.content_type =~ /text\/html/
        html = message.body
        text = nil
      else
        text = message.body
        html = nil
      end
    end

    ::LoggedMail.create(
                        :to => message.to,
                        :reply_to => message.reply_to,
                        :from => message.from,
                        :subject => message.subject,
                        :body => text,
                        :html => html,
                        :raw => message.to_s
                        )
  end
end

app/controllers/logged_mail_controller.rb
class MailDump::LoggedMailController < ActionController::Base
  respond_to :text, :html

  def index
    @mails = LoggedMail.order('created_at DESC').page(params[:p]).per(25)
  end

  def show
    @mail = LoggedMail.find(params[:id])
    respond_to do |format|
      format.html
      format.text { render :format => :html}
    end
  end

  def raw
    @mail = LoggedMail.find(params[:id])
    render :show, :format => :raw
  end

end

app/controllers/mail_dump/application_controller.rb
module MailDump
  class ApplicationController < ActionController::Base
  end
end

app/controllers/mail_dump/logged_mail_controller.rb
class MailDump::LoggedMailController < ActionController::Base
  layout 'mail_dump/application'

  def index
    @mails = LoggedMail.order('created_at DESC').page(params[:p]).per(25)
  end
  
  def show
    @mail = LoggedMail.find(params[:id])
  end
end

app/helpers/mail_dump/application_helper.rb
module MailDump
  module ApplicationHelper
    def output_html(m)
      m.html.respond_to?(:body) ? m.html.body.to_s : m.html
    end
    def output_text(m)
      m.body.respond_to?(:body) ? m.body.body.to_s : m.body
    end
  end
end

app/views/layouts/mail_dump/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MailDump</title>
  <%= stylesheet_link_tag    "mail_dump/application", :media => "all" %>
  <%= javascript_include_tag "mail_dump/application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= link_to "home", logged_mail_index_path %>
  <hr />
  <%= yield %>
</body>
</html>

app/views/mail_dump/logged_mail/_headers.html.erb
<div id="message_headers">
  <dl>
    <dt>From:</dt>
    <dd><%= @mail.from %></dd>
    <% if @mail.reply_to %>
      <dt>Reply-To:</dt>
      <dd><%= @mail.reply_to %></dd>
    <% end %>

    <dt>Subject:</dt>
    <dd><strong><%= @mail.subject %></strong></dd>

    <dt>Date:</dt>
    <dd><%= @mail.created_at.strftime("%b %e, %Y %I:%M:%S %p %Z") %></dd>

    <dt>To:</dt>
    <dd><%= @mail.to %></dd>
  </dl>
</div>
<div id="formats">
  <% if params[:as] != "html" && @mail.has_html? %>
    <%= link_to "view html", logged_mail_path(@mail, :as => "html") %>
  <% end %>
  <% if params[:as] != "text" && @mail.has_text? %>
    <%= link_to "view plaintext", logged_mail_path(@mail, :as => "text") %>
  <% end %>
  <%= link_to "view raw", logged_mail_path(@mail, :as => "raw") %>
</div>

app/views/mail_dump/logged_mail/index.html.erb
<h1>Mail</h1>

<table>
  <tr>
    <th>From</th>
    <th>To</th>
    <th>Subject</th>
    <th>Sent At</th>
    <th>&nbsp;</th>
  </tr>
  <% @mails.each do |mail| -%>
  <tr>
    <%= content_tag(:td, mail.from_addresses) -%>
    <%= content_tag(:td, mail.to_addresses) -%>
    <%= content_tag(:td, mail.subject) -%>
    <%= content_tag(:td, mail.created_at) -%>
    <%= content_tag(:td, link_to('view', url_for(mail))) -%>
  </tr>
  <% end -%>
</table>

<div id="paginator">
  <%= paginate @mails %>
</div>

app/views/mail_dump/logged_mail/show.html.erb
<% params[:as] ||= "html" %>
<%= render 'headers' %>

<% if params[:as] == "html" && @mail.has_html? %>
  <%== output_html @mail %>
<% elsif params[:as] == "raw" %>
  <pre><%= @mail.raw %></pre>
<% else %>
  <pre id="message_body">
    <% if @mail.has_text? %>
      <%= output_text @mail %>
    <% else %>
      (no body)
    <% end %>
  </pre>
<% end %>